version: "3.8"

services:
  backend:
    image: backend-image # デフォルトではビルドしない（開発・本番で指定）
    env_file:
      - ./backend/.env
    networks:
      - app_network

  frontend:
    image: frontend-image # デフォルトではビルドしない（開発・本番で指定）
    env_file:
      - ./frontend/.env.local
    depends_on:
      - backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
