version: "3.8"

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=development
    env_file:
      - ./backend/.env
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    networks:
      - app_network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - ENV=development
    env_file:
      - ./frontend/.env.local
    depends_on:
      - backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
