name: Deploy Backend to Railway

on:
  push:
    branches:
      - main # mainブランチにpushされたら実行

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install/Update Railway CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/railwayapp/cli/main/install.sh | sh
          echo "$HOME/.railway/bin" >> $GITHUB_PATH

      - name: Authenticate Railway
        run: railway login --auth ${{ secrets.RAILWAY_TOKEN }}

      - name: Verify Authentication
        run: railway whoami

      - name: Link Railway Project
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway link --project 2a304d76-4f0f-4f10-8a39-ffb632cca051

      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway up --service backend
