name: Deploy Backend to Railway

on:
  push:
    branches:
      - main # mainブランチにpushされたら実行

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Debug Railway Token
        run: echo "RAILWAY_TOKEN=${{ secrets.RAILWAY_TOKEN }}"

      - name: Deploy to Railway
        run: railway up --service makeMdArticle | true
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
